[project]
name = "py-pieces"
version = "2026.10.0"
description = "Python code pieces"
requires-python = ">=3.15"
dependencies = [
  "anyio>=4.15.1",
  "orjson>=3.13.0",
  "polars>=2.0.0",
  "pydantic>=2.14.0",
  "scikit-learn>=1.9.1",
  "trio>=0.34.0",
]

[dependency-groups]
dev = [
  "ruff>=0.17.0",
  "ty>=0.0.86"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.sources]
"src" = "ulib"

[tool.hatch.build.targets.wheel]
packages = ["src/ulib"]

[tool.uv]
python-preference = "managed"
prerelease = "if-necessary"
resolution = "highest"
